// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCflx9oCQDJqRHuiA-q6ykgT7AtNdfSz6k',
    appId: '1:714926257015:web:9cbdf915e4db15e3b7a772',
    messagingSenderId: '714926257015',
    projectId: 'alpha-zero1',
    authDomain: 'alpha-zero1.firebaseapp.com',
    storageBucket: 'alpha-zero1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXdrPt9p_9prf1kVKatSDMvJMOtKwYa4A',
    appId: '1:714926257015:android:ff5b239167027e26b7a772',
    messagingSenderId: '714926257015',
    projectId: 'alpha-zero1',
    storageBucket: 'alpha-zero1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf_pd4BxsOTP3usdLja9KUjxFFsEj5nVg',
    appId: '1:714926257015:ios:84194d216c82e75bb7a772',
    messagingSenderId: '714926257015',
    projectId: 'alpha-zero1',
    storageBucket: 'alpha-zero1.firebasestorage.app',
    iosBundleId: 'com.example.payper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf_pd4BxsOTP3usdLja9KUjxFFsEj5nVg',
    appId: '1:714926257015:ios:84194d216c82e75bb7a772',
    messagingSenderId: '714926257015',
    projectId: 'alpha-zero1',
    storageBucket: 'alpha-zero1.firebasestorage.app',
    iosBundleId: 'com.example.payper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCflx9oCQDJqRHuiA-q6ykgT7AtNdfSz6k',
    appId: '1:714926257015:web:b063a1979c87b834b7a772',
    messagingSenderId: '714926257015',
    projectId: 'alpha-zero1',
    authDomain: 'alpha-zero1.firebaseapp.com',
    storageBucket: 'alpha-zero1.firebasestorage.app',
  );
}
